// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package localization

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ka": &dictionary{index: kaIndex, data: kaData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"<i class=\\\"fa-solid fa-at text-red-500\\\" aria-hidden=\\\"true\\\"></i>&nbsp;<span class=\\\"font-semibold\\\">Your email address</span>":                                                                            37,
	"<i class=\\\"fa-solid fa-dumpster-fire\\\" aria-hidden=\\\"true\\\"></i>&nbsp;You are not connected to VPN server":                                                                                                      17,
	"<i class=\\\"fa-solid fa-shield-halved\\\" aria-hidden=\\\"true\\\"></i>&nbsp;You are connected to VPN server":                                                                                                          10,
	"<span class=\\\"text-red-500\\\">Failed</span> to create password. Try to start over.":                                                                                                                                  31,
	"<span class=\\\"text-red-500\\\">Legal measures</span> will be taken in case of unauthorized access. The evidence of unauthorized access or any other criminal activity will be reported to law enforcement officials.": 4,
	"Create Password Now!":  38,
	"Create a New Password": 36,
	"Create your VPN password via an email with a <span class=\\\"text-red-500\\\">hyperlink</span>.":                                                                                                       39,
	"Forgot password or IP address changed? Use <a href=\\\"/self-service/\\\" class=\\\"cursor-pointer font-semibold text-gray-700 hover:text-red-500\\\">Self-Service</a> page to create a new password.": 18,
	"G":    25,
	"Gb":   22,
	"Home": 0,
	"K":    23,
	"Kb":   20,
	"M":    24,
	"Mb":   21,
	"N/A":  19,
	"Open-source, modular and portable IPsec-based VPN solution":                                                                                      9,
	"Please save this password in your VPN client settings now. <span class=\\\"text-red-500\\\">You will not be able to view it again later</span>.": 29,
	"Self Service": 1,
	"Something went <span class=\\\"text-red-500\\\">wrong</span>, we are sorry.": 7,
	"Success!": 27,
	"This system is only available for authorized users, <span class=\\\"text-red-500\\\">disconnect immediately</span> if you are not authorized. By accessing this system you accept the contents of the following terms and conditions:": 2,
	"Unauthorized access is <span class=\\\"text-red-500\\\">strictly prohibited</span>.": 3,
	"Usage of this system is recorded. This system is monitored. This system is audited by means of automatic and manual monitoring. Policies are enforced to monitor this system. <span class=\\\"text-red-500\\\">No secrecy or privacy</span> is guaranteed.": 5,
	"VPN: Create Password":      26,
	"VPN: Create Password Fail": 30,
	"VPN: Email Sent":           32,
	"VPN: Error":                6,
	"VPN: Home":                 8,
	"VPN: Self Service":         35,
	"Wait for an Email":         33,
	"Within a few minutes you will receive an email with a create password hyperlink.":                                                                                      34,
	"Your new password for <span class=\\\"text-red-500\\\">%[1]s</span> and <span class=\\\"text-red-500\\\">%[2]s</span> created successfully.":                           28,
	"Your private IP address is <span class=\\\"font-semibold\\\" id=\\\"verification-ip-address\\\"></span>":                                                               16,
	"Your public IP address is <a href=\\\"https://ipinfo.io/%[1]s\\\" target=_blank class=\\\"cursor-pointer font-semibold text-gray-700 hover:text-red-500\\\">%[1]s</a>": 15,
	"bytes":    11,
	"packets":  12,
	"received": 14,
	"sent":     13,
}

var enIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000005, 0x00000012, 0x000000f4,
	0x00000144, 0x00000217, 0x0000030e, 0x00000319,
	0x00000361, 0x0000036b, 0x000003a6, 0x0000040c,
	0x00000412, 0x0000041a, 0x0000041f, 0x00000428,
	0x000004c6, 0x00000526, 0x00000590, 0x0000064e,
	0x00000652, 0x00000655, 0x00000658, 0x0000065b,
	0x0000065d, 0x0000065f, 0x00000661, 0x00000676,
	0x0000067f, 0x00000703, 0x0000078f, 0x000007a9,
	// Entry 20 - 3F
	0x000007fb, 0x0000080b, 0x0000081d, 0x0000086e,
	0x00000880, 0x00000896, 0x00000916, 0x0000092b,
	0x00000987,
} // Size: 188 bytes

const enData string = "" + // Size: 2439 bytes
	"\x02Home\x02Self Service\x02This system is only available for authorized" +
	" users, <span class=\\\x22text-red-500\\\x22>disconnect immediately</spa" +
	"n> if you are not authorized. By accessing this system you accept the co" +
	"ntents of the following terms and conditions:\x02Unauthorized access is " +
	"<span class=\\\x22text-red-500\\\x22>strictly prohibited</span>.\x02<spa" +
	"n class=\\\x22text-red-500\\\x22>Legal measures</span> will be taken in " +
	"case of unauthorized access. The evidence of unauthorized access or any " +
	"other criminal activity will be reported to law enforcement officials." +
	"\x02Usage of this system is recorded. This system is monitored. This sys" +
	"tem is audited by means of automatic and manual monitoring. Policies are" +
	" enforced to monitor this system. <span class=\\\x22text-red-500\\\x22>N" +
	"o secrecy or privacy</span> is guaranteed.\x02VPN: Error\x02Something we" +
	"nt <span class=\\\x22text-red-500\\\x22>wrong</span>, we are sorry.\x02V" +
	"PN: Home\x02Open-source, modular and portable IPsec-based VPN solution" +
	"\x02<i class=\\\x22fa-solid fa-shield-halved\\\x22 aria-hidden=\\\x22tru" +
	"e\\\x22></i>&nbsp;You are connected to VPN server\x02bytes\x02packets" +
	"\x02sent\x02received\x02Your public IP address is <a href=\\\x22https://" +
	"ipinfo.io/%[1]s\\\x22 target=_blank class=\\\x22cursor-pointer font-semi" +
	"bold text-gray-700 hover:text-red-500\\\x22>%[1]s</a>\x02Your private IP" +
	" address is <span class=\\\x22font-semibold\\\x22 id=\\\x22verification-" +
	"ip-address\\\x22></span>\x02<i class=\\\x22fa-solid fa-dumpster-fire\\" +
	"\x22 aria-hidden=\\\x22true\\\x22></i>&nbsp;You are not connected to VPN" +
	" server\x02Forgot password or IP address changed? Use <a href=\\\x22/sel" +
	"f-service/\\\x22 class=\\\x22cursor-pointer font-semibold text-gray-700 " +
	"hover:text-red-500\\\x22>Self-Service</a> page to create a new password." +
	"\x02N/A\x02Kb\x02Mb\x02Gb\x02K\x02M\x02G\x02VPN: Create Password\x02Succ" +
	"ess!\x02Your new password for <span class=\\\x22text-red-500\\\x22>%[1]s" +
	"</span> and <span class=\\\x22text-red-500\\\x22>%[2]s</span> created su" +
	"ccessfully.\x02Please save this password in your VPN client settings now" +
	". <span class=\\\x22text-red-500\\\x22>You will not be able to view it a" +
	"gain later</span>.\x02VPN: Create Password Fail\x02<span class=\\\x22tex" +
	"t-red-500\\\x22>Failed</span> to create password. Try to start over.\x02" +
	"VPN: Email Sent\x02Wait for an Email\x02Within a few minutes you will re" +
	"ceive an email with a create password hyperlink.\x02VPN: Self Service" +
	"\x02Create a New Password\x02<i class=\\\x22fa-solid fa-at text-red-500" +
	"\\\x22 aria-hidden=\\\x22true\\\x22></i>&nbsp;<span class=\\\x22font-sem" +
	"ibold\\\x22>Your email address</span>\x02Create Password Now!\x02Create " +
	"your VPN password via an email with a <span class=\\\x22text-red-500\\" +
	"\x22>hyperlink</span>."

var kaIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000016, 0x00000044, 0x00000287,
	0x00000310, 0x00000549, 0x00000803, 0x0000081e,
	0x00000884, 0x0000089f, 0x00000948, 0x000009f3,
	0x00000a09, 0x00000a22, 0x00000a44, 0x00000a60,
	0x00000b2c, 0x00000bb9, 0x00000c6b, 0x00000df3,
	0x00000dfb, 0x00000e02, 0x00000e09, 0x00000e10,
	0x00000e14, 0x00000e18, 0x00000e1c, 0x00000e4a,
	0x00000e67, 0x00000f4b, 0x00001094, 0x000010e5,
	// Entry 20 - 3F
	0x00001172, 0x000011b0, 0x000011fb, 0x000012af,
	0x000012e2, 0x0000131e, 0x000013ef, 0x0000142f,
	0x00001513,
} // Size: 188 bytes

const kaData string = "" + // Size: 5395 bytes
	"\x02მთავარი\x02თვითმომსახურება\x02ეს სისტემა ხელმისაწვდომია მხოლოდ ავტორ" +
	"იზებული მომხმარებლებისთვის, თუ არ ხართ ავტორიზებული, <span class=\\" +
	"\x22text-red-500\\\x22>დაუყოვნებლივ გათიშეთ კავშირი</span>. ამ სისტემაში" +
	" შესვლით თქვენ ეთანხმებით შემდეგი წესებისა და პირობების შინაარსს:\x02უნე" +
	"ბართვო წვდომა <span class=\\\x22text-red-500\\\x22>მკაცრად აკრძალულია<" +
	"/span>.\x02არაავტორიზებული წვდომის შემთხვევაში მიღებული იქნება <span cla" +
	"ss=\\\x22text-red-500\\\x22>სამართლებრივი ზომები</span>. არაავტორიზებული" +
	" წვდომის ან სხვა ნებისმიერი კრიმინალური საქმიანობის მტკიცებულებები ეცნობ" +
	"ება სამართალდამცავ ორგანოებს.\x02ამ სისტემის გამოყენება აღირიცხება. ეს" +
	" სისტემა მონიტორინგდება. ეს სისტემა აუდიტის ქვეშაა ავტომატური და ხელით მ" +
	"ონიტორინგის საშუალებით. ამ სისტემის მონიტორინგისთვის გამოიყენება პოლიტ" +
	"იკები. <span class=\\\x22text-red-500\\\x22>საიდუმლოება ან კონფიდენცია" +
	"ლურობა არ არის</span> გარანტირებული.\x02VPN: შეცდომა\x02რაღაც მოხდა <s" +
	"pan class=\\\x22text-red-500\\\\\x22>wrong</span>, ვწუხვართ.\x02VPN: მთა" +
	"ვარი\x02ღია კოდის, მოდულური და პორტატული IPsec-ზე დაფუძნებული VPN გადა" +
	"წყვეტა\x02<i class=\\\x22fa-solid fa-shield-halved\\\x22 aria-hidden=" +
	"\\\x22true\\\x22></i>&nbsp;თქვენ დაკავშირებული ხართ VPN სერვერთან\x02ბაი" +
	"ტები\x02პაკეტები\x02გაგზავნილია\x02მიღებულია\x02თქვენი საჯარო IP მისამ" +
	"ართია <a href=\\\x22https://ipinfo.io/%[1]s\\\x22 target=_blank class=" +
	"\\\x22cursor-pointer font-semibold text-gray-700 hover:text-red-500\\" +
	"\x22>%[1]s</a>\x02თქვენი პირადი IP მისამართია <span class=\\\x22font-sem" +
	"ibold\\\x22 id=\\\x22verification-ip-address\\\x22></span>\x02<i class=" +
	"\\\x22fa-solid fa-dumpster-fire\\\x22 aria-hidden=\\\x22true\\\x22></i>&" +
	"nbsp;თქვენ არ ხართ დაკავშირებული VPN სერვერთან\x02პაროლი დაგავიწყდათ ან " +
	"IP მისამართი შეიცვალა? ახალი პაროლის შესაქმნელად გამოიყენეთ <a href=\\" +
	"\x22/self-service/\\\x22 class=\\\x22cursor-pointer font-semibold text-g" +
	"ray-700 hover:text-red-500\\\x22>თვითმომსახურების</a> გვერდი.\x02ა/ხ\x02" +
	"კბ\x02მბ\x02გბ\x02კ\x02მ\x02გ\x02VPN: შექმენი პაროლი\x02წარმატება!\x02" +
	"თქვენი ახალი პაროლი <span class=\\\x22text-red-500\\\x22>%[1]s</span>-" +
	"ისა და <span class=\\\x22text-red-500\\\x22>%[2]s</span>-ისთვის წარმატ" +
	"ებით შეიქმნა.\x02გთხოვთ, ახლავე შეინახოთ ეს პაროლი თქვენი VPN კლიენტის" +
	" პარამეტრებში <span class=\\\x22text-red-500\\\x22>თქვენ მოგვიანებით ვეღ" +
	"არ შეძლებთ მის ნახვას</span>.\x02VPN: პაროლის შექმნა ვერ მოხერხდა\x02პ" +
	"აროლის შექმნა ვერ მოხერხდა. სცადეთ თავიდან დაწყება.\x02VPN: ელ.ფოსტა გ" +
	"აგზავნილია\x02დაელოდეთ ელექტრონულ წერილს\x02რამდენიმე წუთში თქვენ მიიღ" +
	"ებთ წერილს პაროლის შექმნის ჰიპერბმულით.\x02VPN: თვითმომსახურება\x02შექ" +
	"მენით ახალი პაროლი\x02<i class=\\\x22fa-solid fa-at text-red-500\\\x22" +
	" aria-hidden=\\\x22true\\\x22></i>&nbsp;<span class=\\\x22font-semibold" +
	"\\\x22>თქვენი ელექტრონული ფოსტის მისამართი</span>\x02შექმენით პაროლი ახლ" +
	"ავე!\x02შექმენით თქვენი VPN პაროლი ელექტრონული წერილის <span class=\\" +
	"\x22text-red-500\\\x22>ჰიპერბმულის</span> გამოყენებით."

var ruIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000030, 0x000001c2,
	0x00000239, 0x000003e4, 0x00000602, 0x00000614,
	0x0000065d, 0x00000671, 0x000006f5, 0x0000076b,
	0x00000776, 0x00000783, 0x00000798, 0x000007a9,
	0x0000085d, 0x000008ce, 0x00000949, 0x00000a71,
	0x00000a77, 0x00000a7c, 0x00000a81, 0x00000a86,
	0x00000a89, 0x00000a8c, 0x00000a8f, 0x00000ab0,
	0x00000abc, 0x00000b56, 0x00000c42, 0x00000c77,
	// Entry 20 - 3F
	0x00000cfc, 0x00000d3a, 0x00000d79, 0x00000e10,
	0x00000e36, 0x00000e5d, 0x00000efe, 0x00000f28,
	0x00000fcc,
} // Size: 188 bytes

const ruData string = "" + // Size: 4044 bytes
	"\x02Главная\x02Самообслуживание\x02Эта система доступна только для автор" +
	"изованных пользователей, <span class=\\\x22text-red-500\\\x22>немедленн" +
	"о отключитесь</span>, если вы не авторизованы. Получая доступ к этой си" +
	"стеме, вы принимаете содержание следующих положений и условий:\x02Несан" +
	"кционированный доступ <span class=\\\x22text-red-500\\\x22>строго запре" +
	"щен</span>.\x02В случае несанкционированного доступа будут приняты <spa" +
	"n class=\\\x22text-red-500\\\x22>правовые меры</span>. Доказательства не" +
	"санкционированного доступа или любой другой преступной деятельности буд" +
	"ут переданы сотрудникам правоохранительных органов.\x02Использование эт" +
	"ой системы записывается. Эта система контролируется. Эта система провер" +
	"яется с помощью автоматического и ручного мониторинга. Для мониторинга " +
	"этой системы применяются соответствующие политики. <span class=\\\x22te" +
	"xt-red-500\\\x22>Никакая секретность или конфиденциальность</span> не га" +
	"рантируются.\x02VPN: Ошибка\x02Что-то пошло не так, приносим извинения." +
	"\x02VPN: Главная\x02Модульное и портативное решение VPN на базе IPsec с " +
	"открытым исходным кодом\x02<i class=\\\x22fa-solid fa-shield-halved\\" +
	"\x22 aria-hidden=\\\x22true\\\x22></i>&nbsp;Вы подключены к VPN-серверу" +
	"\x02байты\x02пакеты\x02отправлено\x02получено\x02Ваш публичный IP-адрес " +
	"&mdash; <a href=\\\x22https://ipinfo.io/%[1]s\\\x22 target=_blank class=" +
	"\\\x22cursor-pointer font-semibold text-gray-700 hover:text-red-500\\" +
	"\x22>%[1]s</a>\x02Ваш частный IP-адрес &mdash; <span class=\\\x22font-se" +
	"mibold\\\x22 id=\\\x22verification-ip-address\\\x22></span>\x02<i class=" +
	"\\\x22fa-solid fa-dumpster-fire\\\x22 aria-hidden=\\\x22true\\\x22></i>&" +
	"nbsp;Вы не подключены к VPN-серверу\x02Забыли пароль или изменился IP-ад" +
	"рес?  Используйте страницу <a href=\\\x22/self-service/\\\x22 class=\\" +
	"\x22cursor-pointer font-semibold text-gray-700 hover:text-red-500\\\x22>" +
	"самообслуживания</a>, чтобы создать новый пароль.\x02Н/Д\x02Кб\x02Мб" +
	"\x02Гб\x02К\x02М\x02Г\x02VPN: Создать пароль\x02Успех!\x02Ваш новый паро" +
	"ль для <span class=\\\x22text-red-500\\\x22>%[1]s</span> и <span class=" +
	"\\\x22text-red-500\\\x22>%[2]s</span> успешно создан.\x02Пожалуйста, сох" +
	"раните этот пароль в настройках вашего VPN-клиента сейчас. <span class=" +
	"\\\x22text-red-500\\\x22>Вы не сможете просмотреть его позже</span>.\x02" +
	"VPN: Не удалось создать пароль\x02<span class=\\\x22text-red-500\\\x22>Н" +
	"е удалось</span> создать пароль. Попробуйте начать заново.\x02VPN: Элек" +
	"тронное письмо отправлено\x02Ждите письмо по электронной почте\x02В теч" +
	"ение нескольких минут вы получите письмо с гиперссылкой для создания па" +
	"роля.\x02VPN: Самообслуживание\x02Создать новый пароль\x02<i class=\\" +
	"\x22fa-solid fa-at text-red-500\\\x22 aria-hidden=\\\x22true\\\x22></i>&" +
	"nbsp;<span class=\\\x22font-semibold\\\x22>Ваш адрес электронной почты</" +
	"span>\x02Создать пароль сейчас!\x02Создайте свой пароль VPN с помощью эл" +
	"ектронного письма с <span class=\\\x22text-red-500\\\x22>гиперссылкой</" +
	"span>."

	// Total table size 12442 bytes (12KiB); checksum: 4F3AA28E
