# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Branch main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['linux']
        goarch: ['amd64', 'arm64']
        include:
          - goos: 'linux'
            goarch: 'arm64'
            goarm: '7'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        check-latest: true
        cache-dependency-path: ./source/go.sum

    - name: Build
      env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
      run: |
        mkdir -p ./dist/
        go build -C ./source/ -a -v -o -trimpath ./dist/portalswan-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: portalswan-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./dist/portalswan-${{ matrix.goos }}-${{ matrix.goarch }}
